/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  boolean,
  numeric,
  jsonb,
  text,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_admin_users_role = pgEnum("enum_admin_users_role", [
  "super-admin",
  "admin",
  "enquiry-manager",
]);
export const enum_media_media_type = pgEnum("enum_media_media_type", [
  "product",
  "category",
  "banner",
  "hero",
  "gallery",
  "blog",
  "page",
  "heritage",
  "timeline",
  "collection",
  "misc",
]);
export const enum_products_metal = pgEnum("enum_products_metal", [
  "gold",
  "silver",
  "diamond",
  "platinum",
]);
export const enum_categories_metal = pgEnum("enum_categories_metal", [
  "gold",
  "silver",
  "diamond",
  "platinum",
]);
export const enum_blog_posts_body_type = pgEnum("enum_blog_posts_body_type", [
  "h2",
  "p",
  "ul",
]);
export const enum_legal_pages_sections_blocks_type = pgEnum(
  "enum_legal_pages_sections_blocks_type",
  ["p", "ul"],
);
export const enum_inquiries_source = pgEnum("enum_inquiries_source", [
  "contact",
  "enquiry",
]);
export const enum_inquiries_status = pgEnum("enum_inquiries_status", [
  "new",
  "contacted",
  "in-progress",
  "resolved",
  "closed",
  "spam",
]);
export const enum_inquiries_email_notification_status = pgEnum(
  "enum_inquiries_email_notification_status",
  ["not-sent", "sent", "failed"],
);
export const enum_audit_logs_outcome = pgEnum("enum_audit_logs_outcome", [
  "success",
  "failure",
]);

export const admin_users_sessions = pgTable(
  "admin_users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("admin_users_sessions_order_idx").on(columns._order),
    index("admin_users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [admin_users.id],
      name: "admin_users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const admin_users = pgTable(
  "admin_users",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    email: varchar("email").notNull(),
    username: varchar("username"),
    password: varchar("password"),
    role: enum_admin_users_role("role").notNull().default("enquiry-manager"),
    isActive: boolean("is_active").default(true),
    salt: varchar("salt"),
    hash: varchar("hash"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("admin_users_email_idx").on(columns.email),
    uniqueIndex("admin_users_username_idx").on(columns.username),
    index("admin_users_updated_at_idx").on(columns.updatedAt),
    index("admin_users_created_at_idx").on(columns.createdAt),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    mediaType: enum_media_media_type("media_type").default("misc"),
    cloudinaryPublicId: varchar("cloudinary_public_id"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: varchar("sizes_card_filename"),
    sizes_hero_url: varchar("sizes_hero_url"),
    sizes_hero_width: numeric("sizes_hero_width", { mode: "number" }),
    sizes_hero_height: numeric("sizes_hero_height", { mode: "number" }),
    sizes_hero_mimeType: varchar("sizes_hero_mime_type"),
    sizes_hero_filesize: numeric("sizes_hero_filesize", { mode: "number" }),
    sizes_hero_filename: varchar("sizes_hero_filename"),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_card_sizes_card_filename_idx").on(
      columns.sizes_card_filename,
    ),
    index("media_sizes_hero_sizes_hero_filename_idx").on(
      columns.sizes_hero_filename,
    ),
  ],
);

export const products = pgTable(
  "products",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    code: varchar("code"),
    metal: enum_products_metal("metal"),
    category: integer("category_id").references(() => categories.id, {
      onDelete: "set null",
    }),
    weight: varchar("weight"),
    purity: varchar("purity"),
    description: varchar("description"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    seo_title: varchar("seo_title"),
    seo_description: varchar("seo_description"),
    seo_ogImage: integer("seo_og_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("products_slug_idx").on(columns.slug),
    index("products_category_idx").on(columns.category),
    index("products_image_idx").on(columns.image),
    index("products_seo_seo_og_image_idx").on(columns.seo_ogImage),
    index("products_updated_at_idx").on(columns.updatedAt),
    index("products_created_at_idx").on(columns.createdAt),
  ],
);

export const categories = pgTable(
  "categories",
  {
    id: serial("id").primaryKey(),
    metal: enum_categories_metal("metal").notNull(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    displayOrder: numeric("display_order", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("categories_slug_idx").on(columns.slug),
    index("categories_updated_at_idx").on(columns.updatedAt),
    index("categories_created_at_idx").on(columns.createdAt),
  ],
);

export const blog_posts_body_items = pgTable(
  "blog_posts_body_items",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    item: varchar("item"),
  },
  (columns) => [
    index("blog_posts_body_items_order_idx").on(columns._order),
    index("blog_posts_body_items_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [blog_posts_body.id],
      name: "blog_posts_body_items_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const blog_posts_body = pgTable(
  "blog_posts_body",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    type: enum_blog_posts_body_type("type").notNull(),
    text: varchar("text"),
  },
  (columns) => [
    index("blog_posts_body_order_idx").on(columns._order),
    index("blog_posts_body_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [blog_posts.id],
      name: "blog_posts_body_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const blog_posts = pgTable(
  "blog_posts",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    excerpt: varchar("excerpt"),
    date: varchar("date"),
    thumbnail: integer("thumbnail_id").references(() => media.id, {
      onDelete: "set null",
    }),
    seo_title: varchar("seo_title"),
    seo_description: varchar("seo_description"),
    seo_ogImage: integer("seo_og_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("blog_posts_slug_idx").on(columns.slug),
    index("blog_posts_thumbnail_idx").on(columns.thumbnail),
    index("blog_posts_seo_seo_og_image_idx").on(columns.seo_ogImage),
    index("blog_posts_updated_at_idx").on(columns.updatedAt),
    index("blog_posts_created_at_idx").on(columns.createdAt),
  ],
);

export const legal_pages_sections_blocks_items = pgTable(
  "legal_pages_sections_blocks_items",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    item: varchar("item"),
  },
  (columns) => [
    index("legal_pages_sections_blocks_items_order_idx").on(columns._order),
    index("legal_pages_sections_blocks_items_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [legal_pages_sections_blocks.id],
      name: "legal_pages_sections_blocks_items_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const legal_pages_sections_blocks = pgTable(
  "legal_pages_sections_blocks",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    type: enum_legal_pages_sections_blocks_type("type").notNull(),
    text: varchar("text"),
  },
  (columns) => [
    index("legal_pages_sections_blocks_order_idx").on(columns._order),
    index("legal_pages_sections_blocks_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [legal_pages_sections.id],
      name: "legal_pages_sections_blocks_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const legal_pages_sections = pgTable(
  "legal_pages_sections",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    title: varchar("title"),
  },
  (columns) => [
    index("legal_pages_sections_order_idx").on(columns._order),
    index("legal_pages_sections_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [legal_pages.id],
      name: "legal_pages_sections_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const legal_pages = pgTable(
  "legal_pages",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    seo_title: varchar("seo_title"),
    seo_description: varchar("seo_description"),
    seo_ogImage: integer("seo_og_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("legal_pages_slug_idx").on(columns.slug),
    index("legal_pages_seo_seo_og_image_idx").on(columns.seo_ogImage),
    index("legal_pages_updated_at_idx").on(columns.updatedAt),
    index("legal_pages_created_at_idx").on(columns.createdAt),
  ],
);

export const inquiries = pgTable(
  "inquiries",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    email: varchar("email").notNull(),
    phone: varchar("phone"),
    message: varchar("message"),
    city: varchar("city"),
    preferredTime: varchar("preferred_time"),
    productName: varchar("product_name"),
    productId: varchar("product_id"),
    source: enum_inquiries_source("source").default("contact"),
    read: boolean("read").default(false),
    status: enum_inquiries_status("status").default("new"),
    emailNotificationStatus: enum_inquiries_email_notification_status(
      "email_notification_status",
    ).default("not-sent"),
    submittedAt: timestamp("submitted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("inquiries_updated_at_idx").on(columns.updatedAt),
    index("inquiries_created_at_idx").on(columns.createdAt),
  ],
);

export const rate_limits = pgTable(
  "rate_limits",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    count: numeric("count", { mode: "number" }).notNull().default(1),
    resetAt: timestamp("reset_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("rate_limits_key_idx").on(columns.key),
    index("rate_limits_updated_at_idx").on(columns.updatedAt),
    index("rate_limits_created_at_idx").on(columns.createdAt),
  ],
);

export const audit_logs = pgTable(
  "audit_logs",
  {
    id: serial("id").primaryKey(),
    actor: integer("actor_id").references(() => admin_users.id, {
      onDelete: "set null",
    }),
    action: varchar("action").notNull(),
    resourceType: varchar("resource_type"),
    resourceId: varchar("resource_id"),
    metadata: jsonb("metadata"),
    ipHash: varchar("ip_hash"),
    userAgent: varchar("user_agent"),
    outcome: enum_audit_logs_outcome("outcome").notNull().default("success"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("audit_logs_actor_idx").on(columns.actor),
    index("audit_logs_updated_at_idx").on(columns.updatedAt),
    index("audit_logs_created_at_idx").on(columns.createdAt),
  ],
);

export const login_otps = pgTable(
  "login_otps",
  {
    id: serial("id").primaryKey(),
    userId: numeric("user_id", { mode: "number" }).notNull(),
    codeHash: varchar("code_hash").notNull(),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    attempts: numeric("attempts", { mode: "number" }).default(0),
    sessionToken: varchar("session_token"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("login_otps_updated_at_idx").on(columns.updatedAt),
    index("login_otps_created_at_idx").on(columns.createdAt),
  ],
);

export const password_resets = pgTable(
  "password_resets",
  {
    id: serial("id").primaryKey(),
    userId: varchar("user_id").notNull(),
    tokenHash: varchar("token_hash").notNull(),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    used: boolean("used").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("password_resets_updated_at_idx").on(columns.updatedAt),
    index("password_resets_created_at_idx").on(columns.createdAt),
  ],
);

export const reviews = pgTable(
  "reviews",
  {
    id: serial("id").primaryKey(),
    text: varchar("text").notNull(),
    author: varchar("author").notNull(),
    location: varchar("location"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("reviews_updated_at_idx").on(columns.updatedAt),
    index("reviews_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    "admin-usersID": integer("admin_users_id"),
    mediaID: integer("media_id"),
    productsID: integer("products_id"),
    categoriesID: integer("categories_id"),
    "blog-postsID": integer("blog_posts_id"),
    "legal-pagesID": integer("legal_pages_id"),
    inquiriesID: integer("inquiries_id"),
    "rate-limitsID": integer("rate_limits_id"),
    "audit-logsID": integer("audit_logs_id"),
    "login-otpsID": integer("login_otps_id"),
    "password-resetsID": integer("password_resets_id"),
    reviewsID: integer("reviews_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_admin_users_id_idx").on(
      columns["admin-usersID"],
    ),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_products_id_idx").on(
      columns.productsID,
    ),
    index("payload_locked_documents_rels_categories_id_idx").on(
      columns.categoriesID,
    ),
    index("payload_locked_documents_rels_blog_posts_id_idx").on(
      columns["blog-postsID"],
    ),
    index("payload_locked_documents_rels_legal_pages_id_idx").on(
      columns["legal-pagesID"],
    ),
    index("payload_locked_documents_rels_inquiries_id_idx").on(
      columns.inquiriesID,
    ),
    index("payload_locked_documents_rels_rate_limits_id_idx").on(
      columns["rate-limitsID"],
    ),
    index("payload_locked_documents_rels_audit_logs_id_idx").on(
      columns["audit-logsID"],
    ),
    index("payload_locked_documents_rels_login_otps_id_idx").on(
      columns["login-otpsID"],
    ),
    index("payload_locked_documents_rels_password_resets_id_idx").on(
      columns["password-resetsID"],
    ),
    index("payload_locked_documents_rels_reviews_id_idx").on(columns.reviewsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["admin-usersID"]],
      foreignColumns: [admin_users.id],
      name: "payload_locked_documents_rels_admin_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["productsID"]],
      foreignColumns: [products.id],
      name: "payload_locked_documents_rels_products_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["categoriesID"]],
      foreignColumns: [categories.id],
      name: "payload_locked_documents_rels_categories_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["blog-postsID"]],
      foreignColumns: [blog_posts.id],
      name: "payload_locked_documents_rels_blog_posts_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["legal-pagesID"]],
      foreignColumns: [legal_pages.id],
      name: "payload_locked_documents_rels_legal_pages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["inquiriesID"]],
      foreignColumns: [inquiries.id],
      name: "payload_locked_documents_rels_inquiries_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["rate-limitsID"]],
      foreignColumns: [rate_limits.id],
      name: "payload_locked_documents_rels_rate_limits_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["audit-logsID"]],
      foreignColumns: [audit_logs.id],
      name: "payload_locked_documents_rels_audit_logs_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["login-otpsID"]],
      foreignColumns: [login_otps.id],
      name: "payload_locked_documents_rels_login_otps_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["password-resetsID"]],
      foreignColumns: [password_resets.id],
      name: "payload_locked_documents_rels_password_resets_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["reviewsID"]],
      foreignColumns: [reviews.id],
      name: "payload_locked_documents_rels_reviews_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    "admin-usersID": integer("admin_users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_admin_users_id_idx").on(
      columns["admin-usersID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["admin-usersID"]],
      foreignColumns: [admin_users.id],
      name: "payload_preferences_rels_admin_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const site_settings_hero_slides = pgTable(
  "site_settings_hero_slides",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    heading: varchar("heading").notNull(),
    description: varchar("description"),
    ctaText: varchar("cta_text").default("EXPLORE"),
    ctaHref: varchar("cta_href").default("/products"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
  },
  (columns) => [
    index("site_settings_hero_slides_order_idx").on(columns._order),
    index("site_settings_hero_slides_parent_id_idx").on(columns._parentID),
    index("site_settings_hero_slides_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_hero_slides_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_categories = pgTable(
  "site_settings_categories",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    title: varchar("title").notNull(),
    description: varchar("description"),
    ctaText: varchar("cta_text"),
    ctaHref: varchar("cta_href"),
    variant: varchar("variant"),
  },
  (columns) => [
    index("site_settings_categories_order_idx").on(columns._order),
    index("site_settings_categories_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_categories_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_blocks_circle_banner = pgTable(
  "site_settings_blocks_circle_banner",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    title: varchar("title").notNull(),
    description: varchar("description"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    alt: varchar("alt"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("site_settings_blocks_circle_banner_order_idx").on(columns._order),
    index("site_settings_blocks_circle_banner_parent_id_idx").on(
      columns._parentID,
    ),
    index("site_settings_blocks_circle_banner_path_idx").on(columns._path),
    index("site_settings_blocks_circle_banner_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_blocks_circle_banner_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_blocks_image_banner = pgTable(
  "site_settings_blocks_image_banner",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    alt: varchar("alt"),
    title: varchar("title"),
    ctaText: varchar("cta_text"),
    href: varchar("href"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("site_settings_blocks_image_banner_order_idx").on(columns._order),
    index("site_settings_blocks_image_banner_parent_id_idx").on(
      columns._parentID,
    ),
    index("site_settings_blocks_image_banner_path_idx").on(columns._path),
    index("site_settings_blocks_image_banner_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_blocks_image_banner_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_heritage = pgTable(
  "site_settings_heritage",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    heading: varchar("heading"),
    description: varchar("description"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
  },
  (columns) => [
    index("site_settings_heritage_order_idx").on(columns._order),
    index("site_settings_heritage_parent_id_idx").on(columns._parentID),
    index("site_settings_heritage_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_heritage_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_about_page_golden_occasions_paragraphs = pgTable(
  "site_settings_about_page_golden_occasions_paragraphs",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    text: varchar("text"),
  },
  (columns) => [
    index("site_settings_about_page_golden_occasions_paragraphs_order_idx").on(
      columns._order,
    ),
    index(
      "site_settings_about_page_golden_occasions_paragraphs_parent_id_idx",
    ).on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_about_page_golden_occasions_paragraphs_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_about_page_timeline = pgTable(
  "site_settings_about_page_timeline",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    year: varchar("year").notNull(),
    title: varchar("title").notNull(),
    text: varchar("text").notNull(),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
  },
  (columns) => [
    index("site_settings_about_page_timeline_order_idx").on(columns._order),
    index("site_settings_about_page_timeline_parent_id_idx").on(
      columns._parentID,
    ),
    index("site_settings_about_page_timeline_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_about_page_timeline_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_about_page_ventures_bullets = pgTable(
  "site_settings_about_page_ventures_bullets",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    text: varchar("text"),
  },
  (columns) => [
    index("site_settings_about_page_ventures_bullets_order_idx").on(
      columns._order,
    ),
    index("site_settings_about_page_ventures_bullets_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_about_page_ventures_bullets_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_branches = pgTable(
  "site_settings_branches",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    name: varchar("name"),
    address: varchar("address"),
    phone: varchar("phone"),
    phoneFull: varchar("phone_full"),
    email: varchar("email"),
    hours: varchar("hours"),
    mapQ: varchar("map_q"),
    mapEmbedUrl: varchar("map_embed_url"),
  },
  (columns) => [
    index("site_settings_branches_order_idx").on(columns._order),
    index("site_settings_branches_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_branches_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_contact_page_card_items = pgTable(
  "site_settings_contact_page_card_items",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    text: varchar("text"),
  },
  (columns) => [
    index("site_settings_contact_page_card_items_order_idx").on(columns._order),
    index("site_settings_contact_page_card_items_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_contact_page_card_items_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings = pgTable(
  "site_settings",
  {
    id: serial("id").primaryKey(),
    bestsellerProducts: varchar("bestseller_products"),
    aboutPage_goldenOccasions_heading: varchar(
      "about_page_golden_occasions_heading",
    ).default("Golden Occasions & Gleaming Beginnings"),
    aboutPage_goldenOccasions_image: integer(
      "about_page_golden_occasions_image_id",
    ).references(() => media.id, {
      onDelete: "set null",
    }),
    aboutPage_goldenOccasions_alt: varchar(
      "about_page_golden_occasions_alt",
    ).default("About Kerala Jewellers"),
    aboutPage_tasteMeetsTradition_heading: varchar(
      "about_page_taste_meets_tradition_heading",
    ).default("Taste Meets Tradition"),
    aboutPage_tasteMeetsTradition_text: varchar(
      "about_page_taste_meets_tradition_text",
    ),
    aboutPage_origins_heading: varchar("about_page_origins_heading").default(
      "The Origins",
    ),
    aboutPage_origins_intro: varchar("about_page_origins_intro"),
    aboutPage_ventures_heading: varchar("about_page_ventures_heading").default(
      "Our Ventures",
    ),
    aboutPage_ventures_subheading: varchar(
      "about_page_ventures_subheading",
    ).default("Our Dedicated Wedding Hall"),
    aboutPage_ventures_image: integer(
      "about_page_ventures_image_id",
    ).references(() => media.id, {
      onDelete: "set null",
    }),
    aboutPage_ventures_alt: varchar("about_page_ventures_alt"),
    aboutPage_ventures_cta1Text: varchar(
      "about_page_ventures_cta1_text",
    ).default("Know More About Us"),
    aboutPage_ventures_cta1Href: varchar(
      "about_page_ventures_cta1_href",
    ).default("https://www.ayswariyamahal.com/"),
    aboutPage_ventures_cta2Text: varchar(
      "about_page_ventures_cta2_text",
    ).default("Find Us"),
    aboutPage_ventures_cta2Href: varchar(
      "about_page_ventures_cta2_href",
    ).default("https://maps.app.goo.gl/vP759GxjSJLK4oU88"),
    phone: varchar("phone"),
    whatsapp: varchar("whatsapp"),
    email: varchar("email"),
    storeTiming: varchar("store_timing"),
    footerAbout: varchar("footer_about"),
    instagramUrl: varchar("instagram_url"),
    facebookUrl: varchar("facebook_url"),
    youtubeUrl: varchar("youtube_url"),
    homepageSections_bestsellersTitle: varchar(
      "homepage_sections_bestsellers_title",
    ).default("Our Bestsellers"),
    homepageSections_bestsellersSubtitle: varchar(
      "homepage_sections_bestsellers_subtitle",
    ).default(
      "Choose from among trendy designs and timeless pieces. There's something for everyone and every occasion.",
    ),
    homepageSections_latestTitle: varchar(
      "homepage_sections_latest_title",
    ).default("Our Latest"),
    homepageSections_latestSubtitle: varchar(
      "homepage_sections_latest_subtitle",
    ).default(
      "Check out some of the latest designs in our ever-expanding collection.",
    ),
    homepageSections_reviewsTitle: varchar(
      "homepage_sections_reviews_title",
    ).default("Customer Reviews"),
    homepageSections_reviewsSubtitle: varchar(
      "homepage_sections_reviews_subtitle",
    ).default(
      "Our Jewelry Isn't Just Worn. It's Cherished. Each Piece Tells A Story, And You Can Hear It From Our Customers Who Wear Theirs With Pride.",
    ),
    blogPage_promoHeading: varchar("blog_page_promo_heading").default(
      "Wedding Season is here",
    ),
    blogPage_promoDescription: varchar("blog_page_promo_description").default(
      "Embrace the magic of the wedding season with our exquisite jewellery collection. Elevate your bridal ensemble or find the perfect gift for the happy couple with our stunning array of wedding-ready pieces.",
    ),
    blogPage_promoCtaText: varchar("blog_page_promo_cta_text").default(
      "Shop Now",
    ),
    blogPage_promoCtaHref: varchar("blog_page_promo_cta_href").default(
      "/products",
    ),
    blogPage_promoImage: integer("blog_page_promo_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    blogPage_headerTitle: varchar("blog_page_header_title").default("Our Blog"),
    blogPage_headerSubtitle: varchar("blog_page_header_subtitle").default(
      "From Shopping Guides To Lifestyle Recommendations, Explore Our Blog And Learn Everything You Need To Know About Jewellery.",
    ),
    blogPage_emptyText: varchar("blog_page_empty_text").default(
      "Blog posts coming soon. Stay tuned for shopping guides, lifestyle tips, and everything about jewellery.",
    ),
    contactPage_heroTitle: varchar("contact_page_hero_title").default(
      "Contact Kerala Jewellers",
    ),
    contactPage_heroSubtitle: varchar("contact_page_hero_subtitle").default(
      "We're here to help you with store visits, jewellery enquiries, custom designs, and service support.",
    ),
    contactPage_cardTitle: varchar("contact_page_card_title").default(
      "Get In Touch",
    ),
    contactPage_cardDescription: varchar(
      "contact_page_card_description",
    ).default(
      "Looking for a specific jewellery design, bridal collection, custom order, or gold/silver rate update? Our team will guide you with product availability, store visit support, and purchase assistance.",
    ),
    contactPage_cardQuote: varchar("contact_page_card_quote").default(
      "Send us a message and our team will get back to you shortly.",
    ),
    contactPage_branchesTitle: varchar("contact_page_branches_title").default(
      "Our Branches",
    ),
    productsPage_goldHero_title: varchar(
      "products_page_gold_hero_title",
    ).default("Elegant & Timeless Gold Jewellery"),
    productsPage_goldHero_subtitle: varchar(
      "products_page_gold_hero_subtitle",
    ).default(
      "Discover our exclusive collection of gold jewellery that stands the test of time. Perfect for every occasion.",
    ),
    productsPage_silverHero_title: varchar(
      "products_page_silver_hero_title",
    ).default("Classic Elegance in Silver"),
    productsPage_silverHero_subtitle: varchar(
      "products_page_silver_hero_subtitle",
    ).default(
      "Explore our collection of timeless silver jewellery. Perfectly crafted for every moment.",
    ),
    productsPage_diamondHero_title: varchar(
      "products_page_diamond_hero_title",
    ).default("Timeless Brilliance in Diamonds"),
    productsPage_diamondHero_subtitle: varchar(
      "products_page_diamond_hero_subtitle",
    ).default(
      "Discover our exquisite collection of diamond jewellery, crafted to perfection for every occasion.",
    ),
    productsPage_platinumHero_title: varchar(
      "products_page_platinum_hero_title",
    ).default("Exquisite Platinum Jewellery"),
    productsPage_platinumHero_subtitle: varchar(
      "products_page_platinum_hero_subtitle",
    ).default(
      "Explore our refined collection of platinum jewellery, crafted for those who appreciate understated luxury.",
    ),
    rateUpdated: timestamp("rate_updated", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    rateGold22: varchar("rate_gold22"),
    rateGold18: varchar("rate_gold18"),
    rateSilver: varchar("rate_silver"),
    ratePlatinum: varchar("rate_platinum"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("site_settings_about_page_golden_occasions_about_page_gol_idx").on(
      columns.aboutPage_goldenOccasions_image,
    ),
    index("site_settings_about_page_ventures_about_page_ventures_im_idx").on(
      columns.aboutPage_ventures_image,
    ),
    index("site_settings_blog_page_blog_page_promo_image_idx").on(
      columns.blogPage_promoImage,
    ),
  ],
);

export const relations_admin_users_sessions = relations(
  admin_users_sessions,
  ({ one }) => ({
    _parentID: one(admin_users, {
      fields: [admin_users_sessions._parentID],
      references: [admin_users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_admin_users = relations(admin_users, ({ many }) => ({
  sessions: many(admin_users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_products = relations(products, ({ one }) => ({
  category: one(categories, {
    fields: [products.category],
    references: [categories.id],
    relationName: "category",
  }),
  image: one(media, {
    fields: [products.image],
    references: [media.id],
    relationName: "image",
  }),
  seo_ogImage: one(media, {
    fields: [products.seo_ogImage],
    references: [media.id],
    relationName: "seo_ogImage",
  }),
}));
export const relations_categories = relations(categories, () => ({}));
export const relations_blog_posts_body_items = relations(
  blog_posts_body_items,
  ({ one }) => ({
    _parentID: one(blog_posts_body, {
      fields: [blog_posts_body_items._parentID],
      references: [blog_posts_body.id],
      relationName: "items",
    }),
  }),
);
export const relations_blog_posts_body = relations(
  blog_posts_body,
  ({ one, many }) => ({
    _parentID: one(blog_posts, {
      fields: [blog_posts_body._parentID],
      references: [blog_posts.id],
      relationName: "body",
    }),
    items: many(blog_posts_body_items, {
      relationName: "items",
    }),
  }),
);
export const relations_blog_posts = relations(blog_posts, ({ one, many }) => ({
  thumbnail: one(media, {
    fields: [blog_posts.thumbnail],
    references: [media.id],
    relationName: "thumbnail",
  }),
  body: many(blog_posts_body, {
    relationName: "body",
  }),
  seo_ogImage: one(media, {
    fields: [blog_posts.seo_ogImage],
    references: [media.id],
    relationName: "seo_ogImage",
  }),
}));
export const relations_legal_pages_sections_blocks_items = relations(
  legal_pages_sections_blocks_items,
  ({ one }) => ({
    _parentID: one(legal_pages_sections_blocks, {
      fields: [legal_pages_sections_blocks_items._parentID],
      references: [legal_pages_sections_blocks.id],
      relationName: "items",
    }),
  }),
);
export const relations_legal_pages_sections_blocks = relations(
  legal_pages_sections_blocks,
  ({ one, many }) => ({
    _parentID: one(legal_pages_sections, {
      fields: [legal_pages_sections_blocks._parentID],
      references: [legal_pages_sections.id],
      relationName: "blocks",
    }),
    items: many(legal_pages_sections_blocks_items, {
      relationName: "items",
    }),
  }),
);
export const relations_legal_pages_sections = relations(
  legal_pages_sections,
  ({ one, many }) => ({
    _parentID: one(legal_pages, {
      fields: [legal_pages_sections._parentID],
      references: [legal_pages.id],
      relationName: "sections",
    }),
    blocks: many(legal_pages_sections_blocks, {
      relationName: "blocks",
    }),
  }),
);
export const relations_legal_pages = relations(
  legal_pages,
  ({ one, many }) => ({
    seo_ogImage: one(media, {
      fields: [legal_pages.seo_ogImage],
      references: [media.id],
      relationName: "seo_ogImage",
    }),
    sections: many(legal_pages_sections, {
      relationName: "sections",
    }),
  }),
);
export const relations_inquiries = relations(inquiries, () => ({}));
export const relations_rate_limits = relations(rate_limits, () => ({}));
export const relations_audit_logs = relations(audit_logs, ({ one }) => ({
  actor: one(admin_users, {
    fields: [audit_logs.actor],
    references: [admin_users.id],
    relationName: "actor",
  }),
}));
export const relations_login_otps = relations(login_otps, () => ({}));
export const relations_password_resets = relations(password_resets, () => ({}));
export const relations_reviews = relations(reviews, () => ({}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    "admin-usersID": one(admin_users, {
      fields: [payload_locked_documents_rels["admin-usersID"]],
      references: [admin_users.id],
      relationName: "admin-users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    productsID: one(products, {
      fields: [payload_locked_documents_rels.productsID],
      references: [products.id],
      relationName: "products",
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: "categories",
    }),
    "blog-postsID": one(blog_posts, {
      fields: [payload_locked_documents_rels["blog-postsID"]],
      references: [blog_posts.id],
      relationName: "blog-posts",
    }),
    "legal-pagesID": one(legal_pages, {
      fields: [payload_locked_documents_rels["legal-pagesID"]],
      references: [legal_pages.id],
      relationName: "legal-pages",
    }),
    inquiriesID: one(inquiries, {
      fields: [payload_locked_documents_rels.inquiriesID],
      references: [inquiries.id],
      relationName: "inquiries",
    }),
    "rate-limitsID": one(rate_limits, {
      fields: [payload_locked_documents_rels["rate-limitsID"]],
      references: [rate_limits.id],
      relationName: "rate-limits",
    }),
    "audit-logsID": one(audit_logs, {
      fields: [payload_locked_documents_rels["audit-logsID"]],
      references: [audit_logs.id],
      relationName: "audit-logs",
    }),
    "login-otpsID": one(login_otps, {
      fields: [payload_locked_documents_rels["login-otpsID"]],
      references: [login_otps.id],
      relationName: "login-otps",
    }),
    "password-resetsID": one(password_resets, {
      fields: [payload_locked_documents_rels["password-resetsID"]],
      references: [password_resets.id],
      relationName: "password-resets",
    }),
    reviewsID: one(reviews, {
      fields: [payload_locked_documents_rels.reviewsID],
      references: [reviews.id],
      relationName: "reviews",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    "admin-usersID": one(admin_users, {
      fields: [payload_preferences_rels["admin-usersID"]],
      references: [admin_users.id],
      relationName: "admin-users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_site_settings_hero_slides = relations(
  site_settings_hero_slides,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_hero_slides._parentID],
      references: [site_settings.id],
      relationName: "heroSlides",
    }),
    image: one(media, {
      fields: [site_settings_hero_slides.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_site_settings_categories = relations(
  site_settings_categories,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_categories._parentID],
      references: [site_settings.id],
      relationName: "categories",
    }),
  }),
);
export const relations_site_settings_blocks_circle_banner = relations(
  site_settings_blocks_circle_banner,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_blocks_circle_banner._parentID],
      references: [site_settings.id],
      relationName: "_blocks_circleBanner",
    }),
    image: one(media, {
      fields: [site_settings_blocks_circle_banner.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_site_settings_blocks_image_banner = relations(
  site_settings_blocks_image_banner,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_blocks_image_banner._parentID],
      references: [site_settings.id],
      relationName: "_blocks_imageBanner",
    }),
    image: one(media, {
      fields: [site_settings_blocks_image_banner.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_site_settings_heritage = relations(
  site_settings_heritage,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_heritage._parentID],
      references: [site_settings.id],
      relationName: "heritage",
    }),
    image: one(media, {
      fields: [site_settings_heritage.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_site_settings_about_page_golden_occasions_paragraphs =
  relations(
    site_settings_about_page_golden_occasions_paragraphs,
    ({ one }) => ({
      _parentID: one(site_settings, {
        fields: [
          site_settings_about_page_golden_occasions_paragraphs._parentID,
        ],
        references: [site_settings.id],
        relationName: "aboutPage_goldenOccasions_paragraphs",
      }),
    }),
  );
export const relations_site_settings_about_page_timeline = relations(
  site_settings_about_page_timeline,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_about_page_timeline._parentID],
      references: [site_settings.id],
      relationName: "aboutPage_timeline",
    }),
    image: one(media, {
      fields: [site_settings_about_page_timeline.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_site_settings_about_page_ventures_bullets = relations(
  site_settings_about_page_ventures_bullets,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_about_page_ventures_bullets._parentID],
      references: [site_settings.id],
      relationName: "aboutPage_ventures_bullets",
    }),
  }),
);
export const relations_site_settings_branches = relations(
  site_settings_branches,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_branches._parentID],
      references: [site_settings.id],
      relationName: "branches",
    }),
  }),
);
export const relations_site_settings_contact_page_card_items = relations(
  site_settings_contact_page_card_items,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_contact_page_card_items._parentID],
      references: [site_settings.id],
      relationName: "contactPage_cardItems",
    }),
  }),
);
export const relations_site_settings = relations(
  site_settings,
  ({ one, many }) => ({
    heroSlides: many(site_settings_hero_slides, {
      relationName: "heroSlides",
    }),
    categories: many(site_settings_categories, {
      relationName: "categories",
    }),
    _blocks_circleBanner: many(site_settings_blocks_circle_banner, {
      relationName: "_blocks_circleBanner",
    }),
    _blocks_imageBanner: many(site_settings_blocks_image_banner, {
      relationName: "_blocks_imageBanner",
    }),
    heritage: many(site_settings_heritage, {
      relationName: "heritage",
    }),
    aboutPage_goldenOccasions_paragraphs: many(
      site_settings_about_page_golden_occasions_paragraphs,
      {
        relationName: "aboutPage_goldenOccasions_paragraphs",
      },
    ),
    aboutPage_goldenOccasions_image: one(media, {
      fields: [site_settings.aboutPage_goldenOccasions_image],
      references: [media.id],
      relationName: "aboutPage_goldenOccasions_image",
    }),
    aboutPage_timeline: many(site_settings_about_page_timeline, {
      relationName: "aboutPage_timeline",
    }),
    aboutPage_ventures_image: one(media, {
      fields: [site_settings.aboutPage_ventures_image],
      references: [media.id],
      relationName: "aboutPage_ventures_image",
    }),
    aboutPage_ventures_bullets: many(
      site_settings_about_page_ventures_bullets,
      {
        relationName: "aboutPage_ventures_bullets",
      },
    ),
    branches: many(site_settings_branches, {
      relationName: "branches",
    }),
    blogPage_promoImage: one(media, {
      fields: [site_settings.blogPage_promoImage],
      references: [media.id],
      relationName: "blogPage_promoImage",
    }),
    contactPage_cardItems: many(site_settings_contact_page_card_items, {
      relationName: "contactPage_cardItems",
    }),
  }),
);

type DatabaseSchema = {
  enum_admin_users_role: typeof enum_admin_users_role;
  enum_media_media_type: typeof enum_media_media_type;
  enum_products_metal: typeof enum_products_metal;
  enum_categories_metal: typeof enum_categories_metal;
  enum_blog_posts_body_type: typeof enum_blog_posts_body_type;
  enum_legal_pages_sections_blocks_type: typeof enum_legal_pages_sections_blocks_type;
  enum_inquiries_source: typeof enum_inquiries_source;
  enum_inquiries_status: typeof enum_inquiries_status;
  enum_inquiries_email_notification_status: typeof enum_inquiries_email_notification_status;
  enum_audit_logs_outcome: typeof enum_audit_logs_outcome;
  admin_users_sessions: typeof admin_users_sessions;
  admin_users: typeof admin_users;
  media: typeof media;
  products: typeof products;
  categories: typeof categories;
  blog_posts_body_items: typeof blog_posts_body_items;
  blog_posts_body: typeof blog_posts_body;
  blog_posts: typeof blog_posts;
  legal_pages_sections_blocks_items: typeof legal_pages_sections_blocks_items;
  legal_pages_sections_blocks: typeof legal_pages_sections_blocks;
  legal_pages_sections: typeof legal_pages_sections;
  legal_pages: typeof legal_pages;
  inquiries: typeof inquiries;
  rate_limits: typeof rate_limits;
  audit_logs: typeof audit_logs;
  login_otps: typeof login_otps;
  password_resets: typeof password_resets;
  reviews: typeof reviews;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  site_settings_hero_slides: typeof site_settings_hero_slides;
  site_settings_categories: typeof site_settings_categories;
  site_settings_blocks_circle_banner: typeof site_settings_blocks_circle_banner;
  site_settings_blocks_image_banner: typeof site_settings_blocks_image_banner;
  site_settings_heritage: typeof site_settings_heritage;
  site_settings_about_page_golden_occasions_paragraphs: typeof site_settings_about_page_golden_occasions_paragraphs;
  site_settings_about_page_timeline: typeof site_settings_about_page_timeline;
  site_settings_about_page_ventures_bullets: typeof site_settings_about_page_ventures_bullets;
  site_settings_branches: typeof site_settings_branches;
  site_settings_contact_page_card_items: typeof site_settings_contact_page_card_items;
  site_settings: typeof site_settings;
  relations_admin_users_sessions: typeof relations_admin_users_sessions;
  relations_admin_users: typeof relations_admin_users;
  relations_media: typeof relations_media;
  relations_products: typeof relations_products;
  relations_categories: typeof relations_categories;
  relations_blog_posts_body_items: typeof relations_blog_posts_body_items;
  relations_blog_posts_body: typeof relations_blog_posts_body;
  relations_blog_posts: typeof relations_blog_posts;
  relations_legal_pages_sections_blocks_items: typeof relations_legal_pages_sections_blocks_items;
  relations_legal_pages_sections_blocks: typeof relations_legal_pages_sections_blocks;
  relations_legal_pages_sections: typeof relations_legal_pages_sections;
  relations_legal_pages: typeof relations_legal_pages;
  relations_inquiries: typeof relations_inquiries;
  relations_rate_limits: typeof relations_rate_limits;
  relations_audit_logs: typeof relations_audit_logs;
  relations_login_otps: typeof relations_login_otps;
  relations_password_resets: typeof relations_password_resets;
  relations_reviews: typeof relations_reviews;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_site_settings_hero_slides: typeof relations_site_settings_hero_slides;
  relations_site_settings_categories: typeof relations_site_settings_categories;
  relations_site_settings_blocks_circle_banner: typeof relations_site_settings_blocks_circle_banner;
  relations_site_settings_blocks_image_banner: typeof relations_site_settings_blocks_image_banner;
  relations_site_settings_heritage: typeof relations_site_settings_heritage;
  relations_site_settings_about_page_golden_occasions_paragraphs: typeof relations_site_settings_about_page_golden_occasions_paragraphs;
  relations_site_settings_about_page_timeline: typeof relations_site_settings_about_page_timeline;
  relations_site_settings_about_page_ventures_bullets: typeof relations_site_settings_about_page_ventures_bullets;
  relations_site_settings_branches: typeof relations_site_settings_branches;
  relations_site_settings_contact_page_card_items: typeof relations_site_settings_contact_page_card_items;
  relations_site_settings: typeof relations_site_settings;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
